import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const colleges = [
  { name: 'Indian Institute of Technology Bombay', slug: 'iit-bombay', city: 'Mumbai', state: 'Maharashtra', location: 'Mumbai, Maharashtra', type: 'Government', fees: 250000, rating: 4.9, placementRate: 98, avgPackage: 28, established: 1958, affiliatedTo: 'UGC', topRecruiter: ['Google','Microsoft','Amazon','Goldman Sachs','Apple'].join(','), description: 'IIT Bombay is one of India\'s premier engineering institutions known for cutting-edge research and exceptional placements.', courses: [{name:'B.Tech CSE',duration:4,fees:250000,seats:120},{name:'B.Tech EE',duration:4,fees:250000,seats:100},{name:'M.Tech CSE',duration:2,fees:150000,seats:60},{name:'MBA',duration:2,fees:400000,seats:40}], reviews: [{rating:5,body:'World-class faculty and amazing campus life.',author:'Rahul S.'},{rating:4.8,body:'Best placements in India. Rigorous curriculum.',author:'Priya M.'},{rating:4.7,body:'Infrastructure is top-notch. Research opportunities are unmatched.',author:'Amit K.'}] },
  { name: 'Indian Institute of Technology Delhi', slug: 'iit-delhi', city: 'New Delhi', state: 'Delhi', location: 'New Delhi, Delhi', type: 'Government', fees: 240000, rating: 4.8, placementRate: 97, avgPackage: 26, established: 1961, affiliatedTo: 'UGC', topRecruiter: ['Google','Meta','Microsoft','Uber','McKinsey'].join(','), description: 'IIT Delhi is a leading technological university known for innovation, research excellence, and outstanding placement records.', courses: [{name:'B.Tech CSE',duration:4,fees:240000,seats:110},{name:'B.Tech ME',duration:4,fees:240000,seats:90},{name:'M.Tech AI',duration:2,fees:150000,seats:50},{name:'PhD CSE',duration:5,fees:100000,seats:30}], reviews: [{rating:4.9,body:'Excellent research culture and global exposure.',author:'Sneha R.'},{rating:4.7,body:'Campus placements are outstanding every year.',author:'Vikram T.'},{rating:4.8,body:'Great peer group and mentorship.',author:'Ananya P.'}] },
  { name: 'Indian Institute of Technology Madras', slug: 'iit-madras', city: 'Chennai', state: 'Tamil Nadu', location: 'Chennai, Tamil Nadu', type: 'Government', fees: 230000, rating: 4.9, placementRate: 96, avgPackage: 25, established: 1959, affiliatedTo: 'UGC', topRecruiter: ['Google','Microsoft','Samsung','Intel','Qualcomm'].join(','), description: 'IIT Madras consistently ranks #1 in India. Known for its beautiful campus and strong research output.', courses: [{name:'B.Tech CSE',duration:4,fees:230000,seats:100},{name:'B.Tech Data Science',duration:4,fees:230000,seats:80},{name:'M.Tech Robotics',duration:2,fees:140000,seats:40},{name:'BS Data Science',duration:4,fees:200000,seats:200}], reviews: [{rating:5,body:'#1 ranked institute for a reason. Amazing experience.',author:'Karthik V.'},{rating:4.8,body:'Research parks and startup ecosystem are incredible.',author:'Divya S.'},{rating:4.9,body:'Best campus in India, hands down.',author:'Rajan M.'}] },
  { name: 'Indian Institute of Technology Kanpur', slug: 'iit-kanpur', city: 'Kanpur', state: 'Uttar Pradesh', location: 'Kanpur, Uttar Pradesh', type: 'Government', fees: 220000, rating: 4.7, placementRate: 95, avgPackage: 23, established: 1959, affiliatedTo: 'UGC', topRecruiter: ['Google','Microsoft','Adobe','Samsung','Goldman Sachs'].join(','), description: 'IIT Kanpur is renowned for its academic rigor, pioneering CS department, and vibrant campus culture.', courses: [{name:'B.Tech CSE',duration:4,fees:220000,seats:90},{name:'B.Tech EE',duration:4,fees:220000,seats:85},{name:'M.Tech ML',duration:2,fees:140000,seats:45},{name:'MBA',duration:2,fees:380000,seats:35}], reviews: [{rating:4.8,body:'The CS department is legendary.',author:'Deepak J.'},{rating:4.6,body:'Great campus with excellent hostel life.',author:'Manisha K.'},{rating:4.7,body:'Academics are challenging but rewarding.',author:'Suresh P.'}] },
  { name: 'Indian Institute of Technology Kharagpur', slug: 'iit-kharagpur', city: 'Kharagpur', state: 'West Bengal', location: 'Kharagpur, West Bengal', type: 'Government', fees: 220000, rating: 4.7, placementRate: 94, avgPackage: 22, established: 1951, affiliatedTo: 'UGC', topRecruiter: ['TCS','Infosys','Google','Microsoft','Flipkart'].join(','), description: 'IIT Kharagpur, the oldest IIT, is known for its vast campus and diverse academic programs spanning engineering, science, and management.', courses: [{name:'B.Tech CSE',duration:4,fees:220000,seats:95},{name:'B.Tech Civil',duration:4,fees:220000,seats:80},{name:'M.Tech Aerospace',duration:2,fees:140000,seats:30},{name:'MBA',duration:2,fees:370000,seats:40}], reviews: [{rating:4.7,body:'Oldest and one of the best IITs.',author:'Sourav D.'},{rating:4.6,body:'The campus is the largest in Asia. Incredible.',author:'Nilima B.'},{rating:4.5,body:'Strong alumni network globally.',author:'Arjun S.'}] },
  { name: 'National Institute of Technology Trichy', slug: 'nit-trichy', city: 'Tiruchirappalli', state: 'Tamil Nadu', location: 'Tiruchirappalli, Tamil Nadu', type: 'Government', fees: 150000, rating: 4.5, placementRate: 92, avgPackage: 18, established: 1964, affiliatedTo: 'UGC', topRecruiter: ['Zoho','TCS','Infosys','Cognizant','Wipro'].join(','), description: 'NIT Trichy is the top-ranked NIT in India with excellent placements and a strong academic reputation.', courses: [{name:'B.Tech CSE',duration:4,fees:150000,seats:80},{name:'B.Tech ECE',duration:4,fees:150000,seats:75},{name:'M.Tech VLSI',duration:2,fees:100000,seats:30}], reviews: [{rating:4.6,body:'Best NIT in India. Great faculty.',author:'Arun K.'},{rating:4.4,body:'Placements are very good for an NIT.',author:'Meera R.'},{rating:4.5,body:'Beautiful campus and great culture.',author:'Praveen T.'}] },
  { name: 'National Institute of Technology Warangal', slug: 'nit-warangal', city: 'Warangal', state: 'Telangana', location: 'Warangal, Telangana', type: 'Government', fees: 145000, rating: 4.4, placementRate: 90, avgPackage: 16, established: 1959, affiliatedTo: 'UGC', topRecruiter: ['Amazon','Microsoft','Deloitte','TCS','Infosys'].join(','), description: 'NIT Warangal is among the top NITs, known for its strong engineering programs and excellent campus life.', courses: [{name:'B.Tech CSE',duration:4,fees:145000,seats:75},{name:'B.Tech ME',duration:4,fees:145000,seats:70},{name:'M.Tech CSE',duration:2,fees:95000,seats:35}], reviews: [{rating:4.5,body:'One of the best NITs with great placements.',author:'Srinivas M.'},{rating:4.3,body:'Campus is beautiful. Good hostel facilities.',author:'Kavitha P.'},{rating:4.4,body:'Strong alumni network in tech.',author:'Ravi T.'}] },
  { name: 'NIT Surathkal', slug: 'nit-surathkal', city: 'Mangalore', state: 'Karnataka', location: 'Mangalore, Karnataka', type: 'Government', fees: 148000, rating: 4.4, placementRate: 91, avgPackage: 17, established: 1960, affiliatedTo: 'UGC', topRecruiter: ['Cisco','Infosys','TCS','Wipro','Oracle'].join(','), description: 'NITK Surathkal is a premier NIT located on a beautiful beachside campus in Karnataka.', courses: [{name:'B.Tech CSE',duration:4,fees:148000,seats:70},{name:'B.Tech IT',duration:4,fees:148000,seats:65},{name:'M.Tech CSE',duration:2,fees:98000,seats:30}], reviews: [{rating:4.5,body:'Beach campus is absolutely stunning.',author:'Deepa N.'},{rating:4.3,body:'Great academics and placement support.',author:'Girish H.'},{rating:4.4,body:'One of the top NITs in South India.',author:'Pooja S.'}] },
  { name: 'BITS Pilani', slug: 'bits-pilani', city: 'Pilani', state: 'Rajasthan', location: 'Pilani, Rajasthan', type: 'Deemed', fees: 500000, rating: 4.7, placementRate: 95, avgPackage: 22, established: 1964, affiliatedTo: 'UGC', topRecruiter: ['Google','Microsoft','Goldman Sachs','Deutsche Bank','Uber'].join(','), description: 'BITS Pilani is a prestigious private university known for its flexible academic system and outstanding placements.', courses: [{name:'B.E. CSE',duration:4,fees:500000,seats:120},{name:'B.E. EEE',duration:4,fees:500000,seats:100},{name:'M.E. Software Systems',duration:2,fees:350000,seats:40},{name:'MBA',duration:2,fees:600000,seats:50}], reviews: [{rating:4.8,body:'Freedom to explore. Amazing peer group.',author:'Rohit B.'},{rating:4.6,body:'PS-1 and PS-2 internship system is unique and valuable.',author:'Nandini G.'},{rating:4.7,body:'Best private engineering college in India.',author:'Siddharth M.'}] },
  { name: 'Vellore Institute of Technology', slug: 'vit-vellore', city: 'Vellore', state: 'Tamil Nadu', location: 'Vellore, Tamil Nadu', type: 'Deemed', fees: 350000, rating: 4.2, placementRate: 85, avgPackage: 12, established: 1984, affiliatedTo: 'UGC', topRecruiter: ['Cognizant','TCS','Wipro','Infosys','Capgemini'].join(','), description: 'VIT is one of India\'s top private universities with a strong focus on technology and innovation.', courses: [{name:'B.Tech CSE',duration:4,fees:350000,seats:200},{name:'B.Tech ECE',duration:4,fees:340000,seats:150},{name:'B.Tech AI & ML',duration:4,fees:360000,seats:100},{name:'MBA',duration:2,fees:400000,seats:60}], reviews: [{rating:4.3,body:'Good infrastructure and decent placements.',author:'Ajay R.'},{rating:4.1,body:'Campus is well-maintained. Lots of clubs and activities.',author:'Swati M.'},{rating:4.2,body:'International exposure is good.',author:'Varun K.'}] },
  { name: 'SRM Institute of Science and Technology', slug: 'srm-chennai', city: 'Chennai', state: 'Tamil Nadu', location: 'Chennai, Tamil Nadu', type: 'Deemed', fees: 400000, rating: 4.0, placementRate: 80, avgPackage: 10, established: 1985, affiliatedTo: 'UGC', topRecruiter: ['TCS','Infosys','Wipro','HCL','Zoho'].join(','), description: 'SRM is a leading private university with comprehensive programs in engineering, medicine, and management.', courses: [{name:'B.Tech CSE',duration:4,fees:400000,seats:250},{name:'B.Tech ME',duration:4,fees:380000,seats:120},{name:'MBBS',duration:5,fees:2500000,seats:150},{name:'BBA',duration:3,fees:200000,seats:80}], reviews: [{rating:4.1,body:'Good campus and facilities.',author:'Lakshmi V.'},{rating:3.9,body:'Placements vary by branch but CSE is strong.',author:'Dinesh K.'},{rating:4.0,body:'Diverse student community.',author:'Fatima S.'}] },
  { name: 'Manipal Institute of Technology', slug: 'mit-manipal', city: 'Manipal', state: 'Karnataka', location: 'Manipal, Karnataka', type: 'Deemed', fees: 450000, rating: 4.3, placementRate: 88, avgPackage: 14, established: 1957, affiliatedTo: 'Manipal Academy of Higher Education', topRecruiter: ['Amazon','Microsoft','Cisco','SAP','Deloitte'].join(','), description: 'MIT Manipal is renowned for its world-class infrastructure, diverse student body, and comprehensive engineering programs.', courses: [{name:'B.Tech CSE',duration:4,fees:450000,seats:180},{name:'B.Tech ECE',duration:4,fees:440000,seats:120},{name:'B.Tech IT',duration:4,fees:440000,seats:100},{name:'M.Tech Data Science',duration:2,fees:300000,seats:40}], reviews: [{rating:4.4,body:'Amazing campus and student life.',author:'Isha P.'},{rating:4.2,body:'Good mix of academics and extracurriculars.',author:'Aditya S.'},{rating:4.3,body:'International collaborations are excellent.',author:'Neha G.'}] },
  { name: 'Delhi Technological University', slug: 'dtu-delhi', city: 'New Delhi', state: 'Delhi', location: 'New Delhi, Delhi', type: 'Government', fees: 180000, rating: 4.3, placementRate: 89, avgPackage: 16, established: 1941, affiliatedTo: 'UGC', topRecruiter: ['Google','Samsung','Adobe','Oracle','Flipkart'].join(','), description: 'DTU (formerly DCE) is a premier state university in Delhi known for strong engineering programs and vibrant campus culture.', courses: [{name:'B.Tech CSE',duration:4,fees:180000,seats:100},{name:'B.Tech ECE',duration:4,fees:180000,seats:90},{name:'B.Tech IT',duration:4,fees:180000,seats:80},{name:'MBA',duration:2,fees:250000,seats:40}], reviews: [{rating:4.4,body:'Great college with good placements in Delhi.',author:'Mohit S.'},{rating:4.2,body:'Campus culture is vibrant.',author:'Simran K.'},{rating:4.3,body:'DTU has improved massively in recent years.',author:'Aryan T.'}] },
  { name: 'Netaji Subhas University of Technology', slug: 'nsut-delhi', city: 'New Delhi', state: 'Delhi', location: 'New Delhi, Delhi', type: 'Government', fees: 175000, rating: 4.2, placementRate: 87, avgPackage: 15, established: 1983, affiliatedTo: 'UGC', topRecruiter: ['Google','Microsoft','Amazon','Uber','Zomato'].join(','), description: 'NSUT (formerly NSIT) is one of Delhi\'s top engineering institutions with excellent placement records.', courses: [{name:'B.Tech CSE',duration:4,fees:175000,seats:90},{name:'B.Tech ECE',duration:4,fees:175000,seats:85},{name:'B.Tech IT',duration:4,fees:175000,seats:75}], reviews: [{rating:4.3,body:'Strong coding culture and placements.',author:'Kunal M.'},{rating:4.1,body:'Good college for tech placements in Delhi.',author:'Richa S.'},{rating:4.2,body:'Competitive environment that pushes you to excel.',author:'Harsh V.'}] },
  { name: 'IIIT Hyderabad', slug: 'iiit-hyderabad', city: 'Hyderabad', state: 'Telangana', location: 'Hyderabad, Telangana', type: 'Deemed', fees: 280000, rating: 4.6, placementRate: 96, avgPackage: 24, established: 1998, affiliatedTo: 'UGC', topRecruiter: ['Google','Microsoft','Amazon','Uber','Qualcomm'].join(','), description: 'IIIT Hyderabad is a research-driven institution focused exclusively on IT and related areas, with phenomenal placements.', courses: [{name:'B.Tech CSE',duration:4,fees:280000,seats:100},{name:'B.Tech ECE',duration:4,fees:280000,seats:60},{name:'M.Tech CSE',duration:2,fees:200000,seats:50},{name:'PhD CSE',duration:5,fees:120000,seats:25}], reviews: [{rating:4.7,body:'Research culture is top class. Faculty are brilliant.',author:'Shreyas K.'},{rating:4.5,body:'Best for CS in India after IITs.',author:'Tanvi R.'},{rating:4.6,body:'Small batch size means lots of attention.',author:'Prakash V.'}] },
  { name: 'IIT Roorkee', slug: 'iit-roorkee', city: 'Roorkee', state: 'Uttarakhand', location: 'Roorkee, Uttarakhand', type: 'Government', fees: 225000, rating: 4.6, placementRate: 93, avgPackage: 21, established: 1847, affiliatedTo: 'UGC', topRecruiter: ['Google','Microsoft','Goldman Sachs','JPMorgan','Samsung'].join(','), description: 'IIT Roorkee, Asia\'s oldest technical institution, combines heritage with cutting-edge education.', courses: [{name:'B.Tech CSE',duration:4,fees:225000,seats:85},{name:'B.Tech Civil',duration:4,fees:225000,seats:80},{name:'B.Tech ME',duration:4,fees:225000,seats:75},{name:'M.Tech Cyber Security',duration:2,fees:145000,seats:35}], reviews: [{rating:4.7,body:'Historic campus with modern facilities.',author:'Ankit G.'},{rating:4.5,body:'Strong in civil and CS engineering.',author:'Megha S.'},{rating:4.6,body:'Heritage and excellence combined.',author:'Vivek R.'}] },
  { name: 'IIT Guwahati', slug: 'iit-guwahati', city: 'Guwahati', state: 'Assam', location: 'Guwahati, Assam', type: 'Government', fees: 220000, rating: 4.5, placementRate: 92, avgPackage: 20, established: 1994, affiliatedTo: 'UGC', topRecruiter: ['Google','Microsoft','Amazon','Flipkart','Goldman Sachs'].join(','), description: 'IIT Guwahati is known for its scenic campus on the banks of the Brahmaputra and strong academic programs.', courses: [{name:'B.Tech CSE',duration:4,fees:220000,seats:80},{name:'B.Tech EE',duration:4,fees:220000,seats:75},{name:'B.Tech Design',duration:4,fees:220000,seats:40},{name:'M.Tech CSE',duration:2,fees:140000,seats:35}], reviews: [{rating:4.6,body:'Beautiful campus by the Brahmaputra river.',author:'Bhaskar D.'},{rating:4.4,body:'Great for design and CS programs.',author:'Ishita M.'},{rating:4.5,body:'Growing rapidly in rankings.',author:'Nikhil B.'}] },
  { name: 'IIT Hyderabad', slug: 'iit-hyderabad', city: 'Hyderabad', state: 'Telangana', location: 'Hyderabad, Telangana', type: 'Government', fees: 230000, rating: 4.5, placementRate: 91, avgPackage: 19, established: 2008, affiliatedTo: 'UGC', topRecruiter: ['Google','Amazon','Microsoft','Qualcomm','Intel'].join(','), description: 'IIT Hyderabad is one of the new-generation IITs making waves with innovative curriculum and strong research.', courses: [{name:'B.Tech CSE',duration:4,fees:230000,seats:70},{name:'B.Tech AI',duration:4,fees:230000,seats:50},{name:'B.Tech EE',duration:4,fees:230000,seats:65},{name:'M.Tech AI',duration:2,fees:145000,seats:30}], reviews: [{rating:4.6,body:'Best among new IITs. AI program is outstanding.',author:'Sanjay R.'},{rating:4.4,body:'Research-driven approach to education.',author:'Priyanka K.'},{rating:4.5,body:'New campus with state-of-the-art facilities.',author:'Tarun M.'}] },
  { name: 'Indian Institute of Science', slug: 'iisc-bangalore', city: 'Bangalore', state: 'Karnataka', location: 'Bangalore, Karnataka', type: 'Government', fees: 50000, rating: 4.9, placementRate: 90, avgPackage: 24, established: 1909, affiliatedTo: 'UGC', topRecruiter: ['Google','Microsoft','Intel','Qualcomm','Samsung'].join(','), description: 'IISc Bangalore is India\'s top research institution and consistently ranks as the best university in India.', courses: [{name:'B.S. Research',duration:4,fees:50000,seats:120},{name:'M.Tech CSE',duration:2,fees:35000,seats:50},{name:'M.Tech ECE',duration:2,fees:35000,seats:40},{name:'PhD Various',duration:5,fees:25000,seats:200}], reviews: [{rating:5,body:'Best research university in India, period.',author:'Dr. Ramesh K.'},{rating:4.9,body:'World-class faculty and research facilities.',author:'Aakash P.'},{rating:4.8,body:'The campus is 400 acres of green paradise.',author:'Sunitha V.'}] },
  { name: 'College of Engineering Pune', slug: 'coep-pune', city: 'Pune', state: 'Maharashtra', location: 'Pune, Maharashtra', type: 'Government', fees: 120000, rating: 4.2, placementRate: 86, avgPackage: 14, established: 1854, affiliatedTo: 'Savitribai Phule Pune University', topRecruiter: ['TCS','Persistent','Infosys','Cognizant','Cummins'].join(','), description: 'COEP is one of the oldest engineering colleges in Asia, with a rich heritage and strong alumni network.', courses: [{name:'B.Tech CSE',duration:4,fees:120000,seats:80},{name:'B.Tech ME',duration:4,fees:120000,seats:75},{name:'B.Tech IT',duration:4,fees:120000,seats:65}], reviews: [{rating:4.3,body:'Historic college with great reputation in Maharashtra.',author:'Sachin P.'},{rating:4.1,body:'Good placements and strong alumni support.',author:'Ashwini M.'},{rating:4.2,body:'One of the oldest and finest in India.',author:'Ganesh R.'}] },
  { name: 'Jadavpur University', slug: 'jadavpur-university', city: 'Kolkata', state: 'West Bengal', location: 'Kolkata, West Bengal', type: 'Government', fees: 50000, rating: 4.3, placementRate: 82, avgPackage: 12, established: 1955, affiliatedTo: 'UGC', topRecruiter: ['TCS','Wipro','Cognizant','IBM','Accenture'].join(','), description: 'Jadavpur University is a premier state university in Kolkata known for engineering and arts programs at minimal fees.', courses: [{name:'B.Tech CSE',duration:4,fees:50000,seats:70},{name:'B.Tech EE',duration:4,fees:50000,seats:65},{name:'B.Tech ME',duration:4,fees:50000,seats:60},{name:'M.Tech CSE',duration:2,fees:30000,seats:30}], reviews: [{rating:4.4,body:'Best government college in West Bengal.',author:'Subhro C.'},{rating:4.2,body:'Extremely affordable with great education.',author:'Papiya D.'},{rating:4.3,body:'Strong in engineering and liberal arts.',author:'Aniket G.'}] },
  { name: 'Anna University', slug: 'anna-university', city: 'Chennai', state: 'Tamil Nadu', location: 'Chennai, Tamil Nadu', type: 'Government', fees: 65000, rating: 4.1, placementRate: 78, avgPackage: 10, established: 1978, affiliatedTo: 'UGC', topRecruiter: ['TCS','Infosys','Cognizant','Wipro','HCL'].join(','), description: 'Anna University is one of Tamil Nadu\'s largest universities with a vast network of affiliated colleges.', courses: [{name:'B.Tech CSE',duration:4,fees:65000,seats:120},{name:'B.Tech ECE',duration:4,fees:65000,seats:100},{name:'B.Tech Civil',duration:4,fees:65000,seats:80},{name:'MBA',duration:2,fees:120000,seats:60}], reviews: [{rating:4.2,body:'Very affordable with decent placements.',author:'Bala S.'},{rating:4.0,body:'Good for students in Tamil Nadu.',author:'Chandra M.'},{rating:4.1,body:'Large campus and lots of opportunities.',author:'Devi R.'}] },
  { name: 'AIIMS Delhi', slug: 'aiims-delhi', city: 'New Delhi', state: 'Delhi', location: 'New Delhi, Delhi', type: 'Government', fees: 75000, rating: 4.9, placementRate: 100, avgPackage: 20, established: 1956, affiliatedTo: 'Ministry of Health', topRecruiter: ['Apollo Hospitals','Fortis','Max Healthcare','AIIMS Network','WHO'].join(','), description: 'AIIMS Delhi is India\'s top medical institution, setting the gold standard for medical education and healthcare.', courses: [{name:'MBBS',duration:5,fees:75000,seats:100},{name:'MD Medicine',duration:3,fees:50000,seats:40},{name:'MS Surgery',duration:3,fees:50000,seats:30},{name:'B.Sc Nursing',duration:4,fees:25000,seats:60}], reviews: [{rating:5,body:'The best medical college in India without doubt.',author:'Dr. Sharma'},{rating:4.9,body:'World-class clinical exposure and training.',author:'Dr. Gupta'},{rating:4.8,body:'Dream institution for every medical aspirant.',author:'Dr. Patel'}] },
  { name: 'Christian Medical College Vellore', slug: 'cmc-vellore', city: 'Vellore', state: 'Tamil Nadu', location: 'Vellore, Tamil Nadu', type: 'Private', fees: 250000, rating: 4.7, placementRate: 98, avgPackage: 18, established: 1900, affiliatedTo: 'Tamil Nadu Dr MGR Medical University', topRecruiter: ['Apollo','Fortis','CMC Network','Global Hospitals','WHO'].join(','), description: 'CMC Vellore is one of Asia\'s best medical colleges with a 120-year legacy of excellence in healthcare education.', courses: [{name:'MBBS',duration:5,fees:250000,seats:100},{name:'MD Various',duration:3,fees:200000,seats:50},{name:'B.Sc Nursing',duration:4,fees:100000,seats:40}], reviews: [{rating:4.8,body:'Legacy institution with amazing clinical exposure.',author:'Dr. Sarah J.'},{rating:4.6,body:'Patient care philosophy is ingrained in education.',author:'Dr. Thomas K.'},{rating:4.7,body:'Best for compassionate medical training.',author:'Dr. Grace M.'}] },
  { name: 'IIM Ahmedabad', slug: 'iim-ahmedabad', city: 'Ahmedabad', state: 'Gujarat', location: 'Ahmedabad, Gujarat', type: 'Government', fees: 2300000, rating: 4.9, placementRate: 100, avgPackage: 35, established: 1961, affiliatedTo: 'MHRD', topRecruiter: ['McKinsey','BCG','Bain','Goldman Sachs','Amazon'].join(','), description: 'IIM Ahmedabad is India\'s premier management institute, consistently ranked #1 for MBA programs.', courses: [{name:'MBA (PGP)',duration:2,fees:2300000,seats:400},{name:'MBA Food & Agri',duration:2,fees:2100000,seats:40},{name:'PhD Management',duration:5,fees:500000,seats:30}], reviews: [{rating:5,body:'The Harvard of India. Life-changing experience.',author:'Rajesh M.'},{rating:4.9,body:'Network and brand value are unmatched.',author:'Sunita K.'},{rating:4.8,body:'Case study method of learning is incredible.',author:'Amit B.'}] },
  { name: 'IIM Bangalore', slug: 'iim-bangalore', city: 'Bangalore', state: 'Karnataka', location: 'Bangalore, Karnataka', type: 'Government', fees: 2350000, rating: 4.9, placementRate: 100, avgPackage: 34, established: 1973, affiliatedTo: 'MHRD', topRecruiter: ['McKinsey','BCG','Google','Amazon','Goldman Sachs'].join(','), description: 'IIM Bangalore is among the top business schools globally, known for its analytics-driven curriculum.', courses: [{name:'MBA (PGP)',duration:2,fees:2350000,seats:400},{name:'PGPEM',duration:2,fees:2800000,seats:60},{name:'PhD Management',duration:5,fees:500000,seats:25}], reviews: [{rating:4.9,body:'Best MBA program if you are analytics-inclined.',author:'Priya T.'},{rating:4.8,body:'Bangalore location adds immense value.',author:'Vivek S.'},{rating:4.9,body:'Outstanding faculty and curriculum.',author:'Meghna R.'}] },
  { name: 'IIM Calcutta', slug: 'iim-calcutta', city: 'Kolkata', state: 'West Bengal', location: 'Kolkata, West Bengal', type: 'Government', fees: 2200000, rating: 4.8, placementRate: 100, avgPackage: 32, established: 1961, affiliatedTo: 'MHRD', topRecruiter: ['McKinsey','BCG','JPMorgan','Citibank','Accenture'].join(','), description: 'IIM Calcutta is one of the oldest IIMs, known for its finance specialization and strong corporate connections.', courses: [{name:'MBA (PGDM)',duration:2,fees:2200000,seats:460},{name:'PGPEX',duration:1,fees:3000000,seats:55},{name:'PhD',duration:5,fees:400000,seats:20}], reviews: [{rating:4.8,body:'Best for finance specialization.',author:'Soham G.'},{rating:4.7,body:'Heritage campus with world-class education.',author:'Ankita D.'},{rating:4.8,body:'Strong corporate partnerships.',author:'Debashis M.'}] },
  { name: 'Amity University', slug: 'amity-noida', city: 'Noida', state: 'Uttar Pradesh', location: 'Noida, Uttar Pradesh', type: 'Private', fees: 350000, rating: 3.5, placementRate: 70, avgPackage: 8, established: 2005, affiliatedTo: 'UGC', topRecruiter: ['TCS','Wipro','HCL','Cognizant','Tech Mahindra'].join(','), description: 'Amity University is one of India\'s largest private universities offering diverse programs across multiple disciplines.', courses: [{name:'B.Tech CSE',duration:4,fees:350000,seats:300},{name:'BBA',duration:3,fees:250000,seats:200},{name:'B.Sc Psychology',duration:3,fees:200000,seats:100},{name:'LLB',duration:5,fees:300000,seats:80}], reviews: [{rating:3.6,body:'Good campus but placements could be better.',author:'Rahul A.'},{rating:3.4,body:'Wide variety of courses available.',author:'Priti S.'},{rating:3.5,body:'Infrastructure is impressive.',author:'Mohit K.'}] },
  { name: 'Lovely Professional University', slug: 'lpu-jalandhar', city: 'Phagwara', state: 'Punjab', location: 'Phagwara, Punjab', type: 'Private', fees: 300000, rating: 3.4, placementRate: 68, avgPackage: 7, established: 2005, affiliatedTo: 'UGC', topRecruiter: ['TCS','Infosys','Wipro','Byju\'s','Amazon'].join(','), description: 'LPU is one of India\'s largest single-campus universities with students from over 50 countries.', courses: [{name:'B.Tech CSE',duration:4,fees:300000,seats:500},{name:'BBA',duration:3,fees:200000,seats:300},{name:'B.Pharm',duration:4,fees:180000,seats:100},{name:'MBA',duration:2,fees:350000,seats:150}], reviews: [{rating:3.5,body:'Huge campus with lots of facilities.',author:'Gurpreet S.'},{rating:3.3,body:'Good for overall personality development.',author:'Aman K.'},{rating:3.4,body:'International diversity is good.',author:'Neha T.'}] },
  { name: 'Thapar Institute of Engineering', slug: 'thapar-patiala', city: 'Patiala', state: 'Punjab', location: 'Patiala, Punjab', type: 'Deemed', fees: 380000, rating: 4.1, placementRate: 85, avgPackage: 13, established: 1956, affiliatedTo: 'UGC', topRecruiter: ['Google','Amazon','Microsoft','Adobe','Flipkart'].join(','), description: 'Thapar Institute is a premier engineering institution in Punjab known for strong CS placements.', courses: [{name:'B.Tech CSE',duration:4,fees:380000,seats:120},{name:'B.Tech ECE',duration:4,fees:370000,seats:100},{name:'B.Tech ME',duration:4,fees:360000,seats:80},{name:'MBA',duration:2,fees:400000,seats:40}], reviews: [{rating:4.2,body:'Best private engineering college in North India.',author:'Harpreet S.'},{rating:4.0,body:'Good placements especially in CSE.',author:'Ramandeep K.'},{rating:4.1,body:'Campus life is enjoyable.',author:'Jasmine G.'}] },
  { name: 'PSG College of Technology', slug: 'psg-coimbatore', city: 'Coimbatore', state: 'Tamil Nadu', location: 'Coimbatore, Tamil Nadu', type: 'Private', fees: 200000, rating: 4.2, placementRate: 88, avgPackage: 11, established: 1951, affiliatedTo: 'Anna University', topRecruiter: ['Zoho','TCS','Wipro','Bosch','Cognizant'].join(','), description: 'PSG Tech is a top-tier private engineering college in Coimbatore with excellent industry connections.', courses: [{name:'B.Tech CSE',duration:4,fees:200000,seats:90},{name:'B.Tech ECE',duration:4,fees:190000,seats:80},{name:'B.Tech ME',duration:4,fees:185000,seats:70}], reviews: [{rating:4.3,body:'Excellent college with strong industry ties.',author:'Manoj K.'},{rating:4.1,body:'Good placement record consistently.',author:'Santhosh R.'},{rating:4.2,body:'Disciplined environment with good academics.',author:'Kavya M.'}] },
  { name: 'RVCE Bangalore', slug: 'rvce-bangalore', city: 'Bangalore', state: 'Karnataka', location: 'Bangalore, Karnataka', type: 'Private', fees: 280000, rating: 4.1, placementRate: 86, avgPackage: 12, established: 1963, affiliatedTo: 'VTU', topRecruiter: ['Infosys','Wipro','Oracle','Cisco','Samsung'].join(','), description: 'RV College of Engineering is one of Bangalore\'s top private engineering colleges with strong placements.', courses: [{name:'B.Tech CSE',duration:4,fees:280000,seats:120},{name:'B.Tech ECE',duration:4,fees:270000,seats:100},{name:'B.Tech ISE',duration:4,fees:280000,seats:80}], reviews: [{rating:4.2,body:'Top college in Bangalore for engineering.',author:'Sunil M.'},{rating:4.0,body:'Good campus and placement support.',author:'Rashmi S.'},{rating:4.1,body:'Strong alumni in IT industry.',author:'Vinay K.'}] },
  { name: 'PEC Chandigarh', slug: 'pec-chandigarh', city: 'Chandigarh', state: 'Punjab', location: 'Chandigarh, Punjab', type: 'Government', fees: 160000, rating: 4.0, placementRate: 83, avgPackage: 13, established: 1921, affiliatedTo: 'Punjab University', topRecruiter: ['Google','Amazon','TCS','Infosys','Samsung'].join(','), description: 'PEC Chandigarh is one of the oldest and most reputed engineering colleges in North India.', courses: [{name:'B.Tech CSE',duration:4,fees:160000,seats:75},{name:'B.Tech ECE',duration:4,fees:160000,seats:70},{name:'B.Tech ME',duration:4,fees:160000,seats:65}], reviews: [{rating:4.1,body:'Good government college with improving placements.',author:'Gaurav S.'},{rating:3.9,body:'Beautiful Chandigarh campus.',author:'Naina K.'},{rating:4.0,body:'Strong alumni network.',author:'Vikrant M.'}] },
  { name: 'BMS College of Engineering', slug: 'bmsce-bangalore', city: 'Bangalore', state: 'Karnataka', location: 'Bangalore, Karnataka', type: 'Private', fees: 270000, rating: 4.0, placementRate: 84, avgPackage: 11, established: 1946, affiliatedTo: 'VTU', topRecruiter: ['Infosys','TCS','Wipro','Bosch','Samsung'].join(','), description: 'BMSCE is one of Bangalore\'s oldest engineering colleges known for consistent academic performance.', courses: [{name:'B.Tech CSE',duration:4,fees:270000,seats:110},{name:'B.Tech ECE',duration:4,fees:260000,seats:90},{name:'B.Tech ME',duration:4,fees:255000,seats:80}], reviews: [{rating:4.1,body:'One of the best private colleges in Bangalore.',author:'Arun N.'},{rating:3.9,body:'Good placement cell and training.',author:'Bhavya S.'},{rating:4.0,body:'Well-established college with good reputation.',author:'Chetan M.'}] },
  { name: 'NIT Calicut', slug: 'nit-calicut', city: 'Kozhikode', state: 'Kerala', location: 'Kozhikode, Kerala', type: 'Government', fees: 140000, rating: 4.3, placementRate: 89, avgPackage: 15, established: 1961, affiliatedTo: 'UGC', topRecruiter: ['Google','Microsoft','Oracle','TCS','Infosys'].join(','), description: 'NIT Calicut is a top-tier NIT known for excellent academics and placements in Kerala.', courses: [{name:'B.Tech CSE',duration:4,fees:140000,seats:70},{name:'B.Tech ECE',duration:4,fees:140000,seats:65},{name:'B.Tech EE',duration:4,fees:140000,seats:60},{name:'M.Tech CSE',duration:2,fees:90000,seats:30}], reviews: [{rating:4.4,body:'Beautiful campus in Green Kerala.',author:'Anil K.'},{rating:4.2,body:'Strong CS department with good placements.',author:'Deepika R.'},{rating:4.3,body:'One of the best NITs in South India.',author:'Vijay N.'}] },
  { name: 'NIT Rourkela', slug: 'nit-rourkela', city: 'Rourkela', state: 'Odisha', location: 'Rourkela, Odisha', type: 'Government', fees: 142000, rating: 4.2, placementRate: 87, avgPackage: 14, established: 1961, affiliatedTo: 'UGC', topRecruiter: ['TCS','Infosys','Amazon','Microsoft','Tata Steel'].join(','), description: 'NIT Rourkela is a prominent NIT with strong metallurgy and CS programs.', courses: [{name:'B.Tech CSE',duration:4,fees:142000,seats:70},{name:'B.Tech ME',duration:4,fees:142000,seats:65},{name:'B.Tech Metallurgy',duration:4,fees:142000,seats:55}], reviews: [{rating:4.3,body:'Strong technical programs.',author:'Santosh M.'},{rating:4.1,body:'Good campus with modern labs.',author:'Priyanka D.'},{rating:4.2,body:'Improving steadily year over year.',author:'Biswa N.'}] },
  { name: 'IIT BHU Varanasi', slug: 'iit-bhu', city: 'Varanasi', state: 'Uttar Pradesh', location: 'Varanasi, Uttar Pradesh', type: 'Government', fees: 220000, rating: 4.5, placementRate: 92, avgPackage: 20, established: 1919, affiliatedTo: 'UGC', topRecruiter: ['Google','Microsoft','Samsung','Goldman Sachs','Adobe'].join(','), description: 'IIT BHU (formerly IT-BHU) combines the heritage of BHU with the excellence of the IIT system.', courses: [{name:'B.Tech CSE',duration:4,fees:220000,seats:80},{name:'B.Tech Ceramic',duration:4,fees:220000,seats:50},{name:'B.Tech Mining',duration:4,fees:220000,seats:45},{name:'M.Tech CSE',duration:2,fees:140000,seats:30}], reviews: [{rating:4.6,body:'Historic campus in the holy city of Varanasi.',author:'Abhishek Y.'},{rating:4.4,body:'Strong in unique branches like ceramics and mining.',author:'Preeti S.'},{rating:4.5,body:'Great IIT experience with cultural richness.',author:'Ravi V.'}] },
  { name: 'Symbiosis International University', slug: 'symbiosis-pune', city: 'Pune', state: 'Maharashtra', location: 'Pune, Maharashtra', type: 'Deemed', fees: 500000, rating: 4.0, placementRate: 82, avgPackage: 14, established: 1971, affiliatedTo: 'UGC', topRecruiter: ['Deloitte','KPMG','EY','PwC','Accenture'].join(','), description: 'Symbiosis is a prestigious multi-disciplinary university in Pune known for management and law programs.', courses: [{name:'MBA',duration:2,fees:800000,seats:180},{name:'BBA',duration:3,fees:400000,seats:200},{name:'LLB',duration:5,fees:450000,seats:120},{name:'B.Tech CSE',duration:4,fees:500000,seats:80}], reviews: [{rating:4.1,body:'Great for management and law.',author:'Samir P.'},{rating:3.9,body:'Good exposure and industry interaction.',author:'Nandita S.'},{rating:4.0,body:'Beautiful Lavale campus.',author:'Aditya K.'}] },
  { name: 'Chandigarh University', slug: 'chandigarh-university', city: 'Mohali', state: 'Punjab', location: 'Mohali, Punjab', type: 'Private', fees: 320000, rating: 3.8, placementRate: 76, avgPackage: 9, established: 2012, affiliatedTo: 'UGC', topRecruiter: ['TCS','Infosys','Wipro','Cognizant','HCL'].join(','), description: 'Chandigarh University is a fast-growing private university known for diverse programs and modern infrastructure.', courses: [{name:'B.Tech CSE',duration:4,fees:320000,seats:300},{name:'BBA',duration:3,fees:200000,seats:200},{name:'B.Com',duration:3,fees:150000,seats:150},{name:'MBA',duration:2,fees:350000,seats:100}], reviews: [{rating:3.9,body:'Modern campus with good facilities.',author:'Ishaan M.'},{rating:3.7,body:'Growing university with potential.',author:'Priya K.'},{rating:3.8,body:'Good for students who want variety.',author:'Kabir S.'}] },
  { name: 'NIT Nagpur (VNIT)', slug: 'vnit-nagpur', city: 'Nagpur', state: 'Maharashtra', location: 'Nagpur, Maharashtra', type: 'Government', fees: 147000, rating: 4.2, placementRate: 88, avgPackage: 15, established: 1960, affiliatedTo: 'UGC', topRecruiter: ['Google','TCS','Infosys','Microsoft','Amazon'].join(','), description: 'VNIT Nagpur is a top NIT in central India known for strong engineering programs and good placements.', courses: [{name:'B.Tech CSE',duration:4,fees:147000,seats:75},{name:'B.Tech ECE',duration:4,fees:147000,seats:70},{name:'B.Tech Civil',duration:4,fees:147000,seats:60}], reviews: [{rating:4.3,body:'Best engineering college in Vidarbha region.',author:'Amol P.'},{rating:4.1,body:'Good placements and faculty.',author:'Snehal K.'},{rating:4.2,body:'Strong alumni network.',author:'Rajesh D.'}] },
  { name: 'IIT Indore', slug: 'iit-indore', city: 'Indore', state: 'Madhya Pradesh', location: 'Indore, Madhya Pradesh', type: 'Government', fees: 225000, rating: 4.3, placementRate: 90, avgPackage: 18, established: 2009, affiliatedTo: 'UGC', topRecruiter: ['Google','Microsoft','Amazon','Qualcomm','Samsung'].join(','), description: 'IIT Indore is rapidly rising among new-gen IITs with modern campus and strong research output.', courses: [{name:'B.Tech CSE',duration:4,fees:225000,seats:60},{name:'B.Tech EE',duration:4,fees:225000,seats:55},{name:'B.Tech ME',duration:4,fees:225000,seats:50},{name:'M.Tech CSE',duration:2,fees:140000,seats:25}], reviews: [{rating:4.4,body:'Best among newer IITs. Great faculty.',author:'Manish J.'},{rating:4.2,body:'Modern campus with good facilities.',author:'Aparna S.'},{rating:4.3,body:'Growing reputation and placements.',author:'Rohit P.'}] },
  { name: 'St. Xaviers College', slug: 'st-xaviers-mumbai', city: 'Mumbai', state: 'Maharashtra', location: 'Mumbai, Maharashtra', type: 'Private', fees: 80000, rating: 4.1, placementRate: 75, avgPackage: 8, established: 1869, affiliatedTo: 'Mumbai University', topRecruiter: ['Deloitte','KPMG','EY','JPMorgan','HDFC'].join(','), description: 'St. Xavier\'s College Mumbai is one of India\'s most prestigious liberal arts colleges with 150+ years of heritage.', courses: [{name:'B.Sc Physics',duration:3,fees:80000,seats:60},{name:'B.Com',duration:3,fees:70000,seats:120},{name:'BA Economics',duration:3,fees:60000,seats:80},{name:'B.Sc Chemistry',duration:3,fees:80000,seats:50}], reviews: [{rating:4.2,body:'Heritage institution with amazing culture.',author:'Michelle D.'},{rating:4.0,body:'Great for liberal arts education.',author:'Joseph F.'},{rating:4.1,body:'South Mumbai campus is iconic.',author:'Fatima B.'}] },
  { name: 'NIT Allahabad (MNNIT)', slug: 'mnnit-allahabad', city: 'Prayagraj', state: 'Uttar Pradesh', location: 'Prayagraj, Uttar Pradesh', type: 'Government', fees: 143000, rating: 4.1, placementRate: 86, avgPackage: 14, established: 1961, affiliatedTo: 'UGC', topRecruiter: ['Amazon','Microsoft','TCS','Infosys','Flipkart'].join(','), description: 'MNNIT Allahabad is a top NIT in UP known for good academics and improving placements.', courses: [{name:'B.Tech CSE',duration:4,fees:143000,seats:70},{name:'B.Tech ECE',duration:4,fees:143000,seats:65},{name:'B.Tech IT',duration:4,fees:143000,seats:55}], reviews: [{rating:4.2,body:'Good NIT with strong coding culture.',author:'Ashish M.'},{rating:4.0,body:'Improving steadily in rankings.',author:'Sonali G.'},{rating:4.1,body:'Good campus with modern upgrades.',author:'Pankaj Y.'}] },
  { name: 'KIIT University', slug: 'kiit-bhubaneswar', city: 'Bhubaneswar', state: 'Odisha', location: 'Bhubaneswar, Odisha', type: 'Deemed', fees: 350000, rating: 3.9, placementRate: 78, avgPackage: 9, established: 1997, affiliatedTo: 'UGC', topRecruiter: ['TCS','Infosys','Wipro','Cognizant','Accenture'].join(','), description: 'KIIT is a leading private university in Odisha with a sprawling campus and diverse academic programs.', courses: [{name:'B.Tech CSE',duration:4,fees:350000,seats:250},{name:'B.Tech Civil',duration:4,fees:320000,seats:100},{name:'BBA',duration:3,fees:250000,seats:150},{name:'LLB',duration:5,fees:280000,seats:80}], reviews: [{rating:4.0,body:'Beautiful campus and good infrastructure.',author:'Subrat M.'},{rating:3.8,body:'Lots of student activities and events.',author:'Anisha P.'},{rating:3.9,body:'Growing university with good potential.',author:'Raj D.'}] },
  { name: 'IIT Gandhinagar', slug: 'iit-gandhinagar', city: 'Gandhinagar', state: 'Gujarat', location: 'Gandhinagar, Gujarat', type: 'Government', fees: 225000, rating: 4.4, placementRate: 90, avgPackage: 18, established: 2008, affiliatedTo: 'UGC', topRecruiter: ['Google','Microsoft','Qualcomm','Texas Instruments','Goldman Sachs'].join(','), description: 'IIT Gandhinagar is among the best new IITs, known for its liberal engineering approach and beautiful campus.', courses: [{name:'B.Tech CSE',duration:4,fees:225000,seats:55},{name:'B.Tech EE',duration:4,fees:225000,seats:50},{name:'B.Tech ME',duration:4,fees:225000,seats:45},{name:'M.Tech CSE',duration:2,fees:140000,seats:25}], reviews: [{rating:4.5,body:'Beautiful campus with innovative curriculum.',author:'Dhruvil P.'},{rating:4.3,body:'Liberal education approach is unique among IITs.',author:'Neel S.'},{rating:4.4,body:'Small batches mean personal attention.',author:'Krupa M.'}] },
  { name: 'Shiv Nadar University', slug: 'snu-greater-noida', city: 'Greater Noida', state: 'Uttar Pradesh', location: 'Greater Noida, Uttar Pradesh', type: 'Private', fees: 550000, rating: 4.0, placementRate: 82, avgPackage: 13, established: 2011, affiliatedTo: 'UGC', topRecruiter: ['Microsoft','Google','Deloitte','Samsung','Adobe'].join(','), description: 'SNU is a multi-disciplinary research university founded by the HCL founder, known for holistic education.', courses: [{name:'B.Tech CSE',duration:4,fees:550000,seats:120},{name:'B.Tech ECE',duration:4,fees:540000,seats:80},{name:'BBA',duration:3,fees:400000,seats:60},{name:'B.Sc Research',duration:4,fees:450000,seats:50}], reviews: [{rating:4.1,body:'World-class campus and research focus.',author:'Saurav G.'},{rating:3.9,body:'Good for interdisciplinary learning.',author:'Anjali V.'},{rating:4.0,body:'Modern university with great facilities.',author:'Ritik M.'}] },
  { name: 'IIIT Delhi', slug: 'iiit-delhi', city: 'New Delhi', state: 'Delhi', location: 'New Delhi, Delhi', type: 'Government', fees: 320000, rating: 4.4, placementRate: 94, avgPackage: 21, established: 2008, affiliatedTo: 'UGC', topRecruiter: ['Google','Microsoft','Amazon','Adobe','Uber'].join(','), description: 'IIIT Delhi is a state university focused on IT education and research with outstanding placement records.', courses: [{name:'B.Tech CSE',duration:4,fees:320000,seats:120},{name:'B.Tech ECE',duration:4,fees:320000,seats:60},{name:'B.Tech CSAI',duration:4,fees:320000,seats:60},{name:'M.Tech CSE',duration:2,fees:200000,seats:45}], reviews: [{rating:4.5,body:'Best IT-focused institute after IITs.',author:'Arjun S.'},{rating:4.3,body:'Research output is exceptional.',author:'Sakshi M.'},{rating:4.4,body:'Strong placement culture.',author:'Karan P.'}] },
  { name: 'JIPMER Puducherry', slug: 'jipmer-puducherry', city: 'Puducherry', state: 'Tamil Nadu', location: 'Puducherry, Tamil Nadu', type: 'Government', fees: 60000, rating: 4.6, placementRate: 98, avgPackage: 18, established: 1823, affiliatedTo: 'Ministry of Health', topRecruiter: ['JIPMER Network','Apollo','CMC','AIIMS','WHO'].join(','), description: 'JIPMER is one of India\'s oldest and most prestigious medical institutions with nearly 200 years of history.', courses: [{name:'MBBS',duration:5,fees:60000,seats:150},{name:'MD Medicine',duration:3,fees:40000,seats:40},{name:'MS Surgery',duration:3,fees:40000,seats:30},{name:'B.Sc Nursing',duration:4,fees:30000,seats:60}], reviews: [{rating:4.7,body:'Excellent clinical exposure from day one.',author:'Dr. Lakshmi R.'},{rating:4.5,body:'One of the best for medical education in South India.',author:'Dr. Suresh K.'},{rating:4.6,body:'200 years of medical legacy.',author:'Dr. Kumar V.'}] },
  { name: 'NLSIU Bangalore', slug: 'nlsiu-bangalore', city: 'Bangalore', state: 'Karnataka', location: 'Bangalore, Karnataka', type: 'Government', fees: 250000, rating: 4.8, placementRate: 98, avgPackage: 25, established: 1986, affiliatedTo: 'Bar Council of India', topRecruiter: ['AZB','Trilegal','Cyril Amarchand','Khaitan','S&R Associates'].join(','), description: 'NLSIU is India\'s premier law school and the first national law university, setting the standard for legal education.', courses: [{name:'BA LLB',duration:5,fees:250000,seats:80},{name:'LLM',duration:1,fees:200000,seats:40},{name:'PhD Law',duration:5,fees:150000,seats:15}], reviews: [{rating:4.9,body:'The Harvard Law of India.',author:'Adv. Sharma'},{rating:4.7,body:'Moot court culture is unparalleled.',author:'Adv. Reddy'},{rating:4.8,body:'Best legal education in the country.',author:'Adv. Mehta'}] },
  { name: 'NID Ahmedabad', slug: 'nid-ahmedabad', city: 'Ahmedabad', state: 'Gujarat', location: 'Ahmedabad, Gujarat', type: 'Government', fees: 350000, rating: 4.6, placementRate: 95, avgPackage: 18, established: 1961, affiliatedTo: 'Ministry of Commerce', topRecruiter: ['Apple','Google','Samsung','Titan','Asian Paints'].join(','), description: 'NID Ahmedabad is India\'s premier design institute, producing world-class designers for over 60 years.', courses: [{name:'B.Des Product',duration:4,fees:350000,seats:40},{name:'B.Des Communication',duration:4,fees:350000,seats:35},{name:'M.Des Strategic Design',duration:2,fees:400000,seats:25}], reviews: [{rating:4.7,body:'Best design school in Asia.',author:'Prashant M.'},{rating:4.5,body:'Creative freedom is unmatched.',author:'Aditi G.'},{rating:4.6,body:'Portfolio-based education at its finest.',author:'Rahul D.'}] },
];

async function main() {
  console.log('Starting seed...');
  
  // Clear existing data
  await prisma.review.deleteMany();
  await prisma.course.deleteMany();
  await prisma.savedCollege.deleteMany();
  await prisma.savedComparison.deleteMany();
  await prisma.college.deleteMany();

  for (const collegeData of colleges) {
    const { courses, reviews, ...data } = collegeData;
    const college = await prisma.college.create({
      data: {
        ...data,
        totalReviews: reviews.length,
        courses: {
          create: courses,
        },
        reviews: {
          create: reviews,
        },
      },
    });
    console.log(`Created college: ${college.name}`);
  }

  console.log(`Seed completed! Created ${colleges.length} colleges.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
